// Code generated by protoc-gen-gogo. DO NOT EDIT.
// This is a placeholder file for the protobuf generated code.
// In a real implementation, you would generate this file using protoc.

package types

import (
	proto "github.com/gogo/protobuf/proto"
)

// Make GenesisState implement proto.Message
func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (m *GenesisState) Marshal() ([]byte, error) {
	// Simple JSON marshaling as a placeholder
	// In a real implementation, this would use proper protobuf marshaling
	return nil, nil
}
func (m *GenesisState) Unmarshal(data []byte) error {
	// Simple JSON unmarshaling as a placeholder
	// In a real implementation, this would use proper protobuf unmarshaling
	return nil
}
