// Code generated by protoc-gen-gogo. DO NOT EDIT.
// This is a placeholder file for the protobuf generated code.
// In a real implementation, you would generate this file using protoc.

package types

import (
	proto "github.com/gogo/protobuf/proto"
)

// Make TradeEvent implement proto.Message
func (m *TradeEvent) Reset()         { *m = TradeEvent{} }
func (m *TradeEvent) String() string { return proto.CompactTextString(m) }
func (*TradeEvent) ProtoMessage()    {}
func (m *TradeEvent) Marshal() ([]byte, error) {
	// Simple JSON marshaling as a placeholder
	// In a real implementation, this would use proper protobuf marshaling
	return nil, nil
}
func (m *TradeEvent) Unmarshal(data []byte) error {
	// Simple JSON unmarshaling as a placeholder
	// In a real implementation, this would use proper protobuf unmarshaling
	return nil
}

// Make TraderProfile implement proto.Message
func (m *TraderProfile) Reset()         { *m = TraderProfile{} }
func (m *TraderProfile) String() string { return proto.CompactTextString(m) }
func (*TraderProfile) ProtoMessage()    {}
func (m *TraderProfile) Marshal() ([]byte, error) {
	// Simple JSON marshaling as a placeholder
	// In a real implementation, this would use proper protobuf marshaling
	return nil, nil
}
func (m *TraderProfile) Unmarshal(data []byte) error {
	// Simple JSON unmarshaling as a placeholder
	// In a real implementation, this would use proper protobuf unmarshaling
	return nil
}

// Make Params implement proto.Message
func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (m *Params) Marshal() ([]byte, error) {
	// Simple JSON marshaling as a placeholder
	// In a real implementation, this would use proper protobuf marshaling
	return nil, nil
}
func (m *Params) Unmarshal(data []byte) error {
	// Simple JSON unmarshaling as a placeholder
	// In a real implementation, this would use proper protobuf unmarshaling
	return nil
}

// Make GenesisState implement proto.Message
func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (m *GenesisState) Marshal() ([]byte, error) {
	// Simple JSON marshaling as a placeholder
	// In a real implementation, this would use proper protobuf marshaling
	return nil, nil
}
func (m *GenesisState) Unmarshal(data []byte) error {
	// Simple JSON unmarshaling as a placeholder
	// In a real implementation, this would use proper protobuf unmarshaling
	return nil
}
